// SAPQZZA VPN – dark-only theme matching the app design
const colors = {
  light: {
    text: '#FFFFFF',
    tint: '#E040FB',
    background: '#0D0D1A',
    foreground: '#FFFFFF',
    card: '#161628',
    cardForeground: '#FFFFFF',
    primary: '#E040FB',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A2E',
    secondaryForeground: '#AAAACC',
    muted: '#252540',
    mutedForeground: '#8888AA',
    accent: '#E040FB',
    accentForeground: '#FFFFFF',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#252540',
    input: '#252540',
    // VPN-specific tokens
    green: '#00CC6A',
    powerButtonBg: '#1A1A33',
    powerButtonBorder: '#2A2A4A',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#E040FB',
    background: '#0D0D1A',
    foreground: '#FFFFFF',
    card: '#161628',
    cardForeground: '#FFFFFF',
    primary: '#E040FB',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A2E',
    secondaryForeground: '#AAAACC',
    muted: '#252540',
    mutedForeground: '#8888AA',
    accent: '#E040FB',
    accentForeground: '#FFFFFF',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#252540',
    input: '#252540',
    green: '#00CC6A',
    powerButtonBg: '#1A1A33',
    powerButtonBorder: '#2A2A4A',
  },
  radius: 14,
};

export default colors;
